### ISSUE TITLE
Problem with LeakyRelu layer

### ISSUE THREAD

**Issue by madhu-korada** [vijnasu/OpenVINO-Experiments#1]
[ ERROR ]  List of operations that cannot be converted to IE IR:
[ ERROR ]      LeakyRelu (72)
[ ERROR ]          detector/darknet-53/Conv/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_1/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_2/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_3/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_4/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_5/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_6/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_7/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_8/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_9/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_10/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_11/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_12/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_13/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_14/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_15/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_16/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_17/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_18/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_19/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_20/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_21/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_22/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_23/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_24/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_25/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_26/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_27/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_28/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_29/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_30/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_31/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_32/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_33/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_34/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_35/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_36/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_37/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_38/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_39/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_40/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_41/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_42/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_43/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_44/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_45/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_46/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_47/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_48/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_49/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_50/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_51/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_1/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_2/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_3/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_4/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_7/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_8/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_9/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_10/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_11/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_12/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_13/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_15/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_16/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_17/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_18/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_19/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_20/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_21/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_5/LeakyRelu
[ ERROR ]  Part of the nodes was not translated to IE. Stopped.
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #24.

D:\working\openvino\OpenVINO-Experiments\Yolov3\tensorflow-yolo-v3>python "D:/Intel/computer_vision_sdk/deployment_tools/model_optimizer/mo_tf.py" --input_model frozen_darknet_yolov3_model.pb --tensorflow_use_custom_operations_config ..\yolo_v3.json --input_shape [1,416,416,3] --data_type=FP16 --model_name frozen_darknet_yolov3_model_fp16
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      D:\working\openvino\OpenVINO-Experiments\Yolov3\tensorflow-yolo-v3\frozen_darknet_yolov3_model.pb
        - Path for generated IR:        D:\working\openvino\OpenVINO-Experiments\Yolov3\tensorflow-yolo-v3\.
        - IR output name:       frozen_darknet_yolov3_model_fp16
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,416,416,3]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP16
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Offload unsupported operations:       False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Operations to offload:        None
        - Patterns to offload:  None
        - Use the config file:  D:\working\openvino\OpenVINO-Experiments\Yolov3\tensorflow-yolo-v3\..\yolo_v3.json
Model Optimizer version:        1.5.12.49d067a0
[ ERROR ]  List of operations that cannot be converted to IE IR:
[ ERROR ]      LeakyRelu (72)
[ ERROR ]          detector/darknet-53/Conv/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_1/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_2/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_3/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_4/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_5/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_6/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_7/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_8/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_9/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_10/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_11/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_12/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_13/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_14/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_15/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_16/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_17/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_18/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_19/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_20/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_21/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_22/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_23/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_24/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_25/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_26/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_27/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_28/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_29/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_30/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_31/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_32/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_33/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_34/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_35/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_36/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_37/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_38/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_39/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_40/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_41/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_42/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_43/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_44/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_45/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_46/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_47/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_48/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_49/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_50/LeakyRelu
[ ERROR ]          detector/darknet-53/Conv_51/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_1/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_2/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_3/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_4/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_7/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_8/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_9/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_10/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_11/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_12/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_13/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_15/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_16/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_17/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_18/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_19/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_20/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_21/LeakyRelu
[ ERROR ]          detector/yolo-v3/Conv_5/LeakyRelu
[ ERROR ]  Part of the nodes was not translated to IE. Stopped.
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #24.

Can you tell where is the problem. Why does this problem occur to me and not anyone.
Is there anything that is to be changed

**Comment by vijnasu** [comment]
Try to downgrade tensorflow version from 1.13 to 1.12
Refer https://software.intel.com/en-us/forums/computer-vision/topic/805882
